<?php

namespace App\Models\Models;

use App\Observers\ApiuserObserve;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as AuthUser;
use Laravel\Passport\HasApiTokens;
class Apiuser extends AuthUser
{
    use HasFactory,HasApiTokens;
    protected $guarded=[];
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::observe(ApiuserObserve::class);
    }

}
