<?php

namespace App\Models\Models;

use App\Models\admin\FangOwner;
use App\Models\Traits\Fangattr;
use App\Observers\FangObserver;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Fang extends Model
{
    use HasFactory;

    protected $guarded = [];
    protected $appends = ['pic'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::observe(FangObserver::class);
    }

    public function serializeDate(\DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function owner()
    {
        return $this->belongsTo(FangOwner::class, 'fang_owner');
    }

    public function getFangConfigAttribute()
    {
        return explode(',', $this->attributes['fang_config']);
    }

    public function getFangPicAttribute()
    {
        return array_filter(explode('#', $this->attributes['fang_pic']));
    }

    public function attr()
    {
        return $this->belongsTo(Fangattr::class,'','');
    }

    public function getPicAttribute()
    {
        $arr = $this->fang_pic;
        return $arr[1];
    }

    public function relationData()
    {
        $ownerData = FangOwner::get();
//        省份数据
        $citiData = City::where('pid', 0)->get();
//        租期方式
        $fang_rent_type_id = Fangattr::where('filed_name', 'fang_rent_type')->value('id');
        $fang_rent_type_data = Fangattr::where('pid', $fang_rent_type_id)->get();
//        租赁方式
        $fang_rent_class_id = Fangattr::where('filed_name', 'fang_rent_class')->value('id');
        $fang_rent_class_data = Fangattr::where('pid', $fang_rent_class_id)->get();
//        房间朝向
        $fang_direction_id = Fangattr::where('filed_name', 'fang_direction')->value('id');
        $fang_direction_data = Fangattr::where('pid', $fang_direction_id)->get();

//        配套设施
        $fang_config_id = Fangattr::where('filed_name', 'fang_config')->value('id');
        $fang_config_data = Fangattr::where('pid', $fang_config_id)->get();

        return [
            'ownerData' => $ownerData,
            'cityData' => $citiData,
            'fang_rent_type_data' => $fang_rent_type_data,
            'fang_direction_data' => $fang_direction_data,
            'fang_config_data' => $fang_config_data,
            'fang_rent_class_data' => $fang_rent_class_data,
        ];
    }

    public function fangCount()
    {
//        房源总数
        $total = Fang::count();
//        已出租
        $onCount = Fang::where('fang_status', 1)->count();
//        未出租
        $offCount = $total - $onCount;
        return [
            'total' => $total,
            'onCount' => $onCount,
            'offCount' => $offCount,
        ];
    }
}
